name: Publish
on:
    workflow_dispatch:
    push:
         branches:
         - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: '8.0.x'
         
    - name: Restore
      run: dotnet restore ./Mindware_Prototip.sln
      
    - name: Build
      run: dotnet build ./Mindware_Prototip.sln --configuration Release
      
    - name: Publish
      run: dotnet publish ./Mindware_Prototip/Mindware_Prototip.csproj --configuration Release --no-build --output './publish'
      
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
       app-name: mindware-dfcdhdh9b0ajasdd
       publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
       package: "./publish"

    
    
