name: Publish

on:
    workflow_dispatch:
    push:
         branches:
         - master
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
         dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./Mindware_Prototip.sln

    - name: Build
      run: dotnet build ./Mindware_Prototip.sln --configuration Release

    - name: Publish
      run: dotnet publish ./Mindware_Prototip.sln --configuration Release --no-build

    # Azure deployment adımları buradan başlıyor
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.mindware }}
        package: './publish'

    
